### ISSUE TITLE
MySql.Data.MySqlClient.MySqlException not being handled.

### ISSUE THREAD

**Issue by uncled1023** [uncled1023/Combot#4]
Stack Trace:

```
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__5(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

This seems to be a randomly occurring issue.  Maybe due to too many database actions at any given time?

**Comment by uncled1023** [comment]
I have added handling of this in commit https://github.com/uncled1023/Combot/commit/97c4305d783eca2bbb730e3a62505a808862daf1
